name: ai_application_dct
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #router
  #auto_route: ^7.7.1
  go_router: ^10.0.0

  #Core
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.0

  # Android_Speech
  speech_to_text: ^6.3.0
  flutter_pdfview: ^1.3.1
  file_picker: ^5.3.3

  # Camera
  camera: ^0.10.5+2

  path_provider: ^2.0.15
  path: ^1.8.3
  camerawesome: ^1.4.0
  google_mlkit_face_detection: ^0.8.0

  # ui
  circular_progress_bar_with_lines: ^0.0.7
  dotted_border: ^2.0.0+3
  
  # db
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1

  # router
  #auto_route_generator: ^7.2.0
  go_router_builder: ^2.2.4
  
  # Method_Channel
  pigeon: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
