name: ai_application_dct
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.7.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1


  #Android_Speech
  speech_to_text: ^6.3.0
  flutter_pdfview: ^1.3.1
  file_picker: ^5.3.3
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1
  auto_route_generator: ^7.2.0
  
  #Method_Channel
  pigeon: ^10.0.0

flutter:
  uses-material-design: true
